# -*- coding: utf-8 -*-
"""combined_train_desertanimals.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-CPfy6afjbAA5xUcYHVlGVUgSECkHGAj
"""

!nvidia-smi

# Mount Google Drive
from google.colab import drive
drive.mount('/content/gdrive', force_remount=True)

# Create separate directories for each dataset
!mkdir -p /content/dataset1
!mkdir -p /content/dataset2
!mkdir -p /content/combined_dataset/images
!mkdir -p /content/combined_dataset/labels

# Unzip each dataset to its own directory
!unzip -q /content/gdrive/MyDrive/desert-images/ridge.zip -d /content/dataset1
!unzip -q /content/gdrive/MyDrive/desert-images/wash.zip -d /content/dataset2

from google.colab import files
uploaded = files.upload()


!python combine_datasets.py --dataset1 /content/dataset1 --dataset2 /content/dataset2 --output /content/combined_dataset --prefix "ds2_"

!wget -O /content/train_val_split.py https://raw.githubusercontent.com/EdjeElectronics/Train-and-Deploy-YOLO-Models/refs/heads/main/utils/train_val_split.py

# TO DO: Improve robustness of train_val_split.py script so it can handle nested data folders, etc
!python train_val_split.py --datapath="/content/combined_dataset" --train_pct=0.9



!pip install ultralytics

# Python function to automatically create data.yaml config file
# 1. Reads "classes.txt" file to get list of class names
# 2. Creates data dictionary with correct paths to folders, number of classes, and names of classes
# 3. Writes data in YAML format to data.yaml

import yaml
import os

def create_data_yaml(path_to_classes_txt, path_to_data_yaml):

  # Read class.txt to get class names
  if not os.path.exists(path_to_classes_txt):
    print(f'classes.txt file not found! Please create a classes.txt labelmap and move it to {path_to_classes_txt}')
    return
  with open(path_to_classes_txt, 'r') as f:
    classes = []
    for line in f.readlines():
      if len(line.strip()) == 0: continue
      classes.append(line.strip())
  number_of_classes = len(classes)

  # Create data dictionary
  data = {
      'path': '/content/data',
      'train': 'train/images',
      'val': 'validation/images',
      'nc': number_of_classes,
      'names': classes
  }

  # Write data to YAML file
  with open(path_to_data_yaml, 'w') as f:
    yaml.dump(data, f, sort_keys=False)
  print(f'Created config file at {path_to_data_yaml}')

  return

# Define path to classes.txt and run function
path_to_classes_txt = '/content/combined_dataset/classes.txt'
path_to_data_yaml = '/content/data.yaml'

create_data_yaml(path_to_classes_txt, path_to_data_yaml)

print('\nFile contents:\n')
!cat /content/data.yaml

!yolo detect train data=/content/data.yaml model=yolo11s.pt epochs=30 imgsz=640

!yolo detect predict model=runs/detect/train2/weights/best.pt source=data/validation/images save=True

import glob
from IPython.display import Image, display
for image_path in glob.glob(f'/content/runs/detect/predict/*.jpg')[:10]:
  display(Image(filename=image_path, height=400))
  print('\n')

import glob
from IPython.display import Image, display
for image_path in glob.glob(f'/content/runs/detect/predict/*.jpg')[:10]:
  display(Image(filename=image_path, height=400))
  print('\n')

!ls -la /content/runs/detect/train2/weights/

# Commented out IPython magic to ensure Python compatibility.
# Create model folder
!mkdir -p /content/my_model

# Copy model files with correct path
!cp /content/runs/detect/train2/weights/best.pt /content/my_model/my_model.pt
!cp -r /content/runs/detect/train2 /content/my_model

# Zip files
# %cd /content/my_model
!zip /content/my_model.zip my_model.pt
!zip -r /content/my_model.zip train2
# %cd /content

# download my_model.zip file from side bar

from google.colab import files
uploaded = files.upload()

!yolo task=detect mode=predict model=/content/runs/detect/train2/weights/best.pt source=/content/test_video.MP4 save=True

# List the contents of the runs/detect directory to see all folders
!ls -la /content/runs/detect/

!ls -la /content/runs/detect/predict2/

# Install ffmpeg if not already installed
!apt-get install ffmpeg -y

# Convert AVI to MP4
!ffmpeg -i /content/runs/detect/predict2/test_video.avi -c:v libx264 -preset fast -c:a aac /content/converted_video.mp4

# Now display the MP4 version
from IPython.display import HTML
from base64 import b64encode

video_path = '/content/converted_video.mp4'

def show_video(video_path):
  video_file = open(video_path, "rb").read()
  video_url = f"data:video/mp4;base64,{b64encode(video_file).decode()}"
  return HTML(f"""
  <video width=600 controls>
    <source src="{video_url}" type="video/mp4">
  </video>
  """)

show_video(video_path)